apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-postgres-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-postgres
  replicas: 10
  template:
    metadata:
      labels:
        app: springboot-k8s-postgres
    spec:
      containers:
        - name: postgresdbapp
          image: docker.io/shadythedecipher/kikundiwebapp:2.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: postgres
#              valueFrom :
#                configMapKeyRef :
#                  name : db-config
#                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              value: kikundi
#              valueFrom :
#                configMapKeyRef :
#                  name : db-config
#                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              value: postgres
#              valueFrom :
#                secretKeyRef :
#                  name : postgres-secrets
#                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              value: shady987654321
#              valueFrom :
#                secretKeyRef :
#                  name : postgres-secrets
#                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes' resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
