version: '3.1'
services:
  app:
    container_name: kikundi-postgresql
    image: kikundi-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/kikundi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shady987654321
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=shady987654321
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kikundi